* これはなんですか
Windowsで動作するプーアなユーティリティです。過去に必要に迫られて作製
した物ですが、その場しのぎなので、汎用性はあまりありません。

また、特にマニュアルらしきものも準備していません。

* 一覧

** コマンドスクリプト

*** エクスプローラの「送る」からコマンドプロンプトを開く

** 実行ファイル

*** CPU100
優しくCPUを 100% 使いきります。タスクマネージャで確認してみて下さい。
擬似障害用に作製したツールです。

*** ExSleep
指定した時間だけスリープします。

*** MegaFile
巨大なファイルを生成するのを目的に作製したツールです。

*** TVMaker
テスト用のVirusファイルを生成します。

*** UTF8

*** YdmPoorLineEmu
横取り丸のプラグインで通信速度を低速する為に作製しましたが、これは、
MinGWへの移行を完了していません。

*** batkey
*** crlf
*** dedup
重複行を排除するツールです。linux の uniq コマンドと似た機能を持ちます
が、複数行に渡って繰返している行を排除します。

例えば以下のようなファイルを
#+BEGIN_SRC xml
 <referenced_column>37</referenced_column>
 <referenced_column>118</referenced_column>
 <referenced_column>37</referenced_column>
 <referenced_column>118</referenced_column>
 <referenced_column>37</referenced_column>
 <referenced_column>118</referenced_column>
 <referenced_column>37</referenced_column>
 <referenced_column>118</referenced_column>
 <relation>7</relation>
 <relation>6</relation>
 <relation>7</relation>
 <relation>6</relation>
 <relation>7</relation>
 <relation>6</relation>
#+END_SRC
以下のように圧縮します。
#+BEGIN_SRC xml
 <referenced_column>37</referenced_column>
 <referenced_column>118</referenced_column>
 <relation>7</relation>
 <relation>6</relation>
#+END_SRC

*** img2java
*** lha32

*** tee

Linux の tee コマンドのクローンです。標準出力とファイルの両方に出力す
るコマンドです。

*** wlsfonts

* Build

MinGW(x86_64-w64-mingw32-gcc (GCC) 7.4.0)でbuildできます。元々はVC6と
Cygwinのgccを使用していましたが、現在はMinGWに統一しました。ソースコー
ドもutf-8に統一しています。scrディレクトリで
#+BEGIN_EXAMPLE
make
#+END_EXAMPLE
と入力する事により、全ての実行ファイルをbinディレクトリへ生成します。
詳細は、makefile を参照して下さい。

** 私の環境以外で修正が必要なmakefile

src/lha32/makefile は修正が必要になるかもしれません。

UNLHA32.DLLのヘッダファイルとライブラリファイルを使用しています。これ
らのファイルが別途必要になります。

 - [[https://micco.mars.jp/mysoft/unlha32.htm%0A][UNLHA32.DLL for Win32]]

等から別途入手してインストールして下さい。そして、当該ファイルの先頭付
近の

#+BEGIN_EXAMPLE
UNLHA_BASE_DIR="/Program Files (x86)/ArchiverDll/UNLHA32"
#+END_EXAMPLE
の部分を適切に書換えて下さい。

# Local Variables:
# coding: utf-8
# End:
