* これはなんですか
Windowsで動作するプーアなユーティリティです。
過去に必要に迫られて作製した物ですが、その場しのぎなので、
汎用性はあまりありません。

また、特にマニュアルらしきものも準備していません。

* 一覧

** コマンドスクリプト

*** エクスプローラの「送る」からコマンドプロンプトを開く


** 実行ファイル

*** CPU100
優しくCPUを 100% 使いきります。タスクマネージャで確認してみて下さい。
擬似障害用に作製したツールです。

*** ExSleep
指定した時間だけスリープします。

*** MegaFile
巨大なファイルを生成するのを目的に作製したツールです。

*** TVMaker
テスト用のVirusファイルを生成します。

*** UTF8
utf-8 に関連する変換クラスを作成しましたが、現在は、
ノーメンテナンスです。

*** YdmPoorLineEmu
横取り丸のプラグインで通信速度を低速する為に作製しましたが、
これは、MinGWへの移行を完了していません。
今後も移行予定はありません。

*** batkey
コマンドスクリプト内でキー入力を得る為に作成しましたが、
コマンドスクリプトでも
#+begin_example
SET /P 変数=[プロンプト文字列]
#+end_example
で行なう事ができるので、不要なコマンドかもしれません。

*** crlf
テキストファイルの改行コードを CR+LF に変換します。
元々はメモ帳でファイルを参照する時の為に作成したのですが、
最近は LF のみでも正しく表示できるので、最早不要なツールです。

*** dedup
重複行を排除するツールです。linux の uniq
コマンドと似た機能を持ちますが、複数行に渡って繰返している行を排除します。

例えば以下のようなファイルを
#+BEGIN_SRC xml
 <referenced_column>37</referenced_column>
 <referenced_column>118</referenced_column>
 <referenced_column>37</referenced_column>
 <referenced_column>118</referenced_column>
 <referenced_column>37</referenced_column>
 <referenced_column>118</referenced_column>
 <referenced_column>37</referenced_column>
 <referenced_column>118</referenced_column>
 <relation>7</relation>
 <relation>6</relation>
 <relation>7</relation>
 <relation>6</relation>
 <relation>7</relation>
 <relation>6</relation>
#+END_SRC
以下のように圧縮します。
#+BEGIN_SRC xml
 <referenced_column>37</referenced_column>
 <referenced_column>118</referenced_column>
 <relation>7</relation>
 <relation>6</relation>
#+END_SRC

*** img2java
*** lha32
lhaコマンドの実装です。

*** tee
Linux の tee コマンドのクローンです。
標準出力とファイルの両方に出力するコマンドです。

*** wlsfonts
フォントの一覧を列挙するコマンドです。

*** weekNumber
特定の曜日の週番号と日付を列挙します。

* Build

MinGW(x86_64-w64-mingw32-gcc (GCC) 7.4.0)でbuildできます。元々は VC6
とCygwinのgccを使用していましたが、現在はMinGWに統一しました。
ソースコードもutf-8に統一しています。scrディレクトリで
#+BEGIN_EXAMPLE
cmake -B out -G Ninja
ninja -C out
#+END_EXAMPLE
と入力する事により、全ての実行ファイルをbinディレクトリへ生成します。
詳細は、=src/CMakeLists.txt= を参照して下さい。

元々は makefile で記述していましたが、現在は cmake で記述しています。
makefile が残っている場合もありますが、何れ削除する予定です。

** 私の環境以外で修正が必要な CMakeLists.txt

src/lha32/CMakeLists.txt は修正が必要になります。

UNLHA32.DLLのヘッダファイルとライブラリファイルを使用しています。
これらのファイルが別途必要になります。

 - [[https://micco.mars.jp/mysoft/unlha32.htm%0A][UNLHA32.DLL for Win32]]

等から別途入手してインストールして下さい。そして、
当該ファイルの先頭付近の

#+BEGIN_EXAMPLE
include_directories(${CMAKE_CURRENT_SOURCE_DIR}/../../../../work/UNLHA32)
link_directories(${CMAKE_CURRENT_SOURCE_DIR}/../../../../work/UNLHA32)
#+END_EXAMPLE
の部分を適切に書換えて下さい。

# Local Variables:
# coding: utf-8
# End:
